/* Clause 22 audit workflow: vendor summaries, overrides, FY workspaces and reconciliation. */
(()=>{
 const key="msme1_workflow_v1",read=()=>{try{return JSON.parse(localStorage.getItem(key)||"{}")}catch{return{}}},write=x=>localStorage.setItem(key,JSON.stringify(x));
 let state=read();state.vendors??={};state.overrides??={};state.audit??=[];state.workspaces??={};let activeClient=state.activeWorkspace?.client||"",activeFY=state.activeWorkspace?.fy||"2025-26";
 const escHtml=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
 function inject(){
  const nav=document.getElementById("nav"),main=document.querySelector(".main");
  const b=document.createElement("button");b.textContent="🧾 Audit Tools";b.dataset.page="auditTools";nav.appendChild(b);
  const p=document.createElement("section");p.id="auditTools";p.className="page";p.innerHTML='<div class="top"><div><h1>Audit Tools</h1><p>Clause 22 review, due-date overrides, workspace selection and reconciliation.</p></div></div><div class="panel row"><label>Client <select id="wfClient"></select></label><label>Financial year <select id="wfFY"><option>2025-26</option><option>2024-25</option><option>2026-27</option></select></label><button class="primary" id="wfSelect">Open workspace</button></div><div class="cards"><div class="card"><span>Invoices</span><b id="wfCount">0</b></div><div class="card"><span>Unmatched payment value</span><b id="wfUnmatched">₹0</b></div><div class="card"><span>Invoices missing vendor</span><b id="wfMissing">0</b></div><div class="card"><span>Overrides with audit reason</span><b id="wfOverrides">0</b></div></div><div class="panel"><h2>Vendor-wise Clause 22 summary</h2><table><thead><tr><th>Vendor</th><th>Invoices</th><th>Invoice value</th><th>Paid within time</th><th>Delayed / unpaid</th><th>Outstanding</th><th>Interest working</th></tr></thead><tbody id="wfVendorSummary"></tbody></table></div><div class="panel"><h2>Vendor defaults</h2><div class="row"><input id="wfVendorName" placeholder="Vendor name"><select id="wfVendorStatus"><option>MSE</option><option>Non-MSE</option><option>Review</option></select><input id="wfVendorCredit" type="number" min="0" placeholder="Default credit days"><button id="wfVendorSave" class="primary">Save default</button></div><div id="wfVendorList"></div></div><div class="panel"><h2>Invoice due-date overrides</h2><p>Use the override action in the invoice schedule. A reason is required and each change is recorded.</p><div id="wfOverrideList"></div></div><div class="panel"><h2>Reconciliation</h2><p id="wfReconcileSummary">Process SAP data to reconcile payments and vendors.</p><div id="wfReconDetails"></div><ul id="wfReconcileList"></ul></div><div class="panel"><h2>Audit trail</h2><table><thead><tr><th>When</th><th>Client</th><th>FY</th><th>Invoice</th><th>Original due date</th><th>New due date</th><th>Reason</th></tr></thead><tbody id="wfAudit"></tbody></table></div>';
  main.appendChild(p);
  document.getElementById("wfSelect").onclick=()=>{const oldKey=(activeClient||"Default")+"|"+activeFY;state.workspaces[oldKey]??={created:new Date().toISOString()};state.workspaces[oldKey].rows=JSON.parse(localStorage.getItem("msme1_rows")||"[]");state.workspaces[oldKey].vendors=JSON.parse(localStorage.getItem("msme1_vendors")||"[]");activeClient=document.getElementById("wfClient").value||"Default";activeFY=document.getElementById("wfFY").value;const k=activeClient+"|"+activeFY;state.workspaces[k]??={created:new Date().toISOString(),rows:[],vendors:[]};state.activeWorkspace={client:activeClient,fy:activeFY};write(state);localStorage.setItem("msme1_rows",JSON.stringify(state.workspaces[k].rows||[]));localStorage.setItem("msme1_vendors",JSON.stringify(state.workspaces[k].vendors||[]));location.reload()};
  document.getElementById("wfVendorSave").onclick=()=>{const name=document.getElementById("wfVendorName").value.trim();if(!name)return;state.vendors[name.toLowerCase()]={name,status:document.getElementById("wfVendorStatus").value,credit:Number(document.getElementById("wfVendorCredit").value)||0};write(state);document.getElementById("wfVendorName").value="";render()};
  render();
 }
 function fmtDate(d){return d instanceof Date&&!isNaN(d)?d.toLocaleDateString("en-IN"):"—"}
 function render(){
  const v=typeof invoices==="undefined"?[]:invoices,rate=Number(document.getElementById("rate")?.value||15)/100,groups={};
  v.forEach(x=>{let name=x.vendor||"Unknown";groups[name]??={n:0,amount:0,paid:0,late:0,out:0,int:0};let g=groups[name];g.n++;g.amount+=x.amount||0;g.paid+=x.paidByDue||0;g.late+=x.delayedAmount||0;g.out+=x.outstanding||0;g.int+=(x.delayedAmount||0)*rate*(x.delay||0)/365});
  const body=document.getElementById("wfVendorSummary");if(body)body.innerHTML=Object.values(groups).map(g=>'<tr><td>'+escHtml(g.name)+'</td><td>'+g.n+'</td><td>'+money(g.amount)+'</td><td>'+money(g.paid)+'</td><td>'+money(g.late)+'</td><td>'+money(g.out)+'</td><td>'+money(g.int)+'</td></tr>').join("")||'<tr><td colspan="7">No invoice data.</td></tr>';
  const count=document.getElementById("wfCount");if(count)count.textContent=v.length;
  const wk=activeClient+"|"+activeFY+"|";const os=Object.entries(state.overrides).filter(([k])=>k.startsWith(wk));document.getElementById("wfOverrides").textContent=os.length;
  const au=document.getElementById("wfAudit");au.innerHTML=state.audit.filter(a=>a.client===activeClient&&a.fy===activeFY).slice().reverse().map(a=>'<tr><td>'+escHtml(new Date(a.at).toLocaleString())+'</td><td>'+escHtml(a.client)+'</td><td>'+escHtml(a.fy)+'</td><td>'+escHtml(a.invoice)+'</td><td>'+escHtml(a.from)+'</td><td>'+escHtml(a.to)+'</td><td>'+escHtml(a.reason)+'</td></tr>').join("")||'<tr><td colspan="5">No overrides recorded.</td></tr>';
  document.getElementById("wfVendorList").innerHTML=Object.values(state.vendors).map(x=>'<p>'+escHtml(x.name)+' · '+escHtml(x.status)+' · '+(x.credit||"—")+' credit days</p>').join("")||"No vendor defaults.";
  document.getElementById("wfClient").innerHTML=[...new Set([...((typeof clients!=="undefined"?clients:[]).map(c=>c.name)),activeClient].filter(Boolean))].map(x=>'<option>'+escHtml(x)+'</option>').join("");
  document.getElementById("wfClient").value=activeClient||document.getElementById("wfClient").value;
  document.getElementById("wfFY").value=activeFY;
  const mismatch=v.filter(x=>!x.vendor||x.vendor==="Unknown").length;document.getElementById("wfMissing").textContent=mismatch;
  const sourceRows=typeof rows!=="undefined"?rows:[],rec=(typeof auditResult!=="undefined"&&auditResult)||fifoMatch(sourceRows,{}),payments=rec?.unmatchedPayments||[],unmatched=payments.reduce((s,x)=>s+(x.remaining||0),0);document.getElementById("wfUnmatched").textContent=money(unmatched);
  const missing=v.filter(x=>!x.vendor||x.vendor==="Unknown"),items=[];if(unmatched)items.push("Unmatched payments: "+payments.filter(x=>x.remaining>0).length+" payment row(s), "+money(unmatched)+".");if(mismatch)items.push("Missing vendor: "+mismatch+" invoice(s) need vendor identification.");if(!items.length)items.push("No unmatched payments or missing invoice vendors found.");document.getElementById("wfReconcileList").innerHTML=items.map(x=>"<li>"+escHtml(x)+"</li>").join("");const paymentRows=payments.filter(x=>x.remaining>0).map(x=>'<tr><td>'+escHtml(x.sr)+'</td><td>'+escHtml(x.vendor||"Unknown")+'</td><td>'+escHtml(fmtDate(x.date))+'</td><td>'+money(x.remaining)+'</td></tr>').join("")||'<tr><td colspan="4">No unmatched payments.</td></tr>';document.getElementById("wfReconDetails").innerHTML='<h3>Unmatched payments</h3><table><thead><tr><th>Payment row</th><th>Vendor</th><th>Payment date</th><th>Unmatched amount</th></tr></thead><tbody>'+paymentRows+'</tbody></table><h3>Invoices missing vendor</h3><p>'+ (missing.map(x=>'Invoice '+escHtml(x.sr)+' · '+money(x.amount)).join("<br>")||"No invoices missing vendor.")+'</p>';
  document.getElementById("wfReconcileSummary").textContent="Reconciliation for "+(activeClient||"Default client")+" · FY "+activeFY+".";
  const ov=document.getElementById("wfOverrideList");ov.innerHTML=v.map(x=>'<div class="row wf-ov"><span>Invoice '+escHtml(x.sr)+' · current due '+fmtDate(x.due)+'</span><input type="date" aria-label="New due date for invoice '+escHtml(x.sr)+'"><input placeholder="Mandatory override reason" aria-label="Reason for invoice '+escHtml(x.sr)+'"><button class="primary">Apply</button></div>').join("")||"Process invoices to add an override.";
  [...ov.querySelectorAll(".wf-ov")].forEach((el,i)=>el.querySelector("button").onclick=()=>{let x=v[i],date=el.querySelector('input[type="date"]').value,reason=el.querySelector('input[placeholder]').value.trim();if(!date||!reason){alert("Choose a due date and enter a reason.");return}const from=fmtDate(x.due);state.overrides[activeClient+"|"+activeFY+"|"+String(x.sr)]={date,reason};state.audit.push({at:new Date().toISOString(),client:activeClient,fy:activeFY,invoice:String(x.sr),from,to:fmtDate(new Date(date+"T00:00:00")),reason});write(state);if(typeof buildInvoices==="function")buildInvoices();if(typeof renderAll==="function")renderAll();render()});
 }
 const oldPaste=window.processPaste;window.processPaste=function(){if(oldPaste)oldPaste();rows=rows.map(r=>{const d=state.vendors[(r.vendor||"").toLowerCase()];return d&&d.credit?{...r,credit:d.credit}:r});auditResult=fifoMatch(rows,{defaultCreditPeriod:Number(document.getElementById("defaultCredit")?.value)||45});buildInvoices();renderAll();const k=(activeClient||"Default")+"|"+activeFY;state.workspaces[k]??={created:new Date().toISOString()};state.workspaces[k].rows=JSON.parse(localStorage.getItem("msme1_rows")||"[]");write(state)};
 const oldRender=window.renderAll;window.renderAll=function(){if(oldRender)oldRender();render()};
 const oldBuild=window.buildInvoices;window.buildInvoices=function(){if(oldBuild)oldBuild();if(typeof invoices!=="undefined")invoices=invoices.map(x=>{const o=state.overrides[activeClient+"|"+activeFY+"|"+String(x.sr)];if(!o)return x;const due=new Date(o.date+"T00:00:00"),paidByDue=x.payments.filter(p=>p.date&&p.date<=due).reduce((a,p)=>a+p.amount,0),delayedAmount=Math.max(0,x.amount-paidByDue),outstanding=Math.max(0,x.amount-x.paidTotal),fy=new Date(document.getElementById("fyEnd").value||"2026-03-31"),last=x.payments.length?x.payments[x.payments.length-1].date:null,delay=last?Math.max(0,Math.round((last-due)/86400000)):Math.max(0,Math.round((fy-due)/86400000));return{...x,due,paidByDue,delayedAmount,outstanding,delay}})};
 const oldAddVendor=window.addVendor;window.addVendor=function(){if(oldAddVendor)oldAddVendor();if(typeof vendors!=="undefined"){vendors=vendors.map(v=>{const d=state.vendors[(v.name||"").toLowerCase()];return d?{...v,status:d.status}:v});localStorage.setItem("msme1_vendors",JSON.stringify(vendors))}render()};
 document.addEventListener("click",e=>{const btn=e.target.closest('#nav button[data-page="auditTools"]');if(btn){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));document.getElementById("auditTools").classList.add("active");document.querySelectorAll("#nav button").forEach(x=>x.classList.toggle("active",x===btn));render()}});
 if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",inject);else inject();
})();
